security/generator/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from security.settings import DEBUG
from . import views

app_name = "generator"
urlpatterns = [
    path("",views.IndexTemplate.as_view(), name="index-page"),
] 
htmx_patterns = [
    path("form-data",views.FormData.as_view(),name="form-data")
]
urlpatterns += htmx_patterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

security/security/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("generator.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

security/generator/models.py
from email.policy import default
from django.db import models
from django.db.models import Q
import qrcode
from io import BytesIO
from PIL import Image, ImageDraw
from django.core.files import File
from django.contrib.auth.models import User
# Create your models here.

class Student(models.Model):    
    """
    students model for database
    """
    os_list= (("windows","Windows"),("harmony","harmony"),("ubuntu","ubuntu"),("ios","ios"),("android","android"),("linux","linux"))
    qr_code = models.ImageField(upload_to="QR",help_text="student image",blank=True,editable=False)
    first_name = models.CharField(max_length=19,help_text="student first name")
    last_name = models.CharField(max_length=19,help_text="student last name")
    email = models.EmailField(help_text="student email")
    reg_no = models.CharField(max_length=16,help_text="registration number ")
    gadget_brand = models.CharField(max_length=15,help_text="e.g. hp")
    gadget_model = models.CharField(max_length=15,help_text="folio 9470")
    gadget_serial = models.CharField(max_length=15,help_text="CNU4149***")
    gadget_os = models.CharField(max_length=8,choices=os_list)
    reg_date= models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.reg_no}"








security/generator/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.base import View
from django.http import HttpResponse
from .models import Student
# Create your views here.


class IndexTemplate(TemplateView):
    template_name = "index.html"
   

#htmx views
class FormData(View):
    def get(self,request,*args,**kwargs):
        data = request.GET.get("reg","")
        qs = Student.objects.filter(reg_no__iexact=data)
        return render(request,"results.html",{"qs":qs})

security/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}" />
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}" />
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}" />
    <link rel="manifest" href="{% static 'img/site.webmanifest' %}" />
    <link rel="stylesheet" href="{% static 'img/site.webmanifest' %}" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <title>QR-code generator</title>
</head>

<body>
    <nav >
        <img src="{% static 'img/apple-touch-icon.png' %}" alt="" class="qr">
        <h3 class="header-text">Download you QR code here</h3>
        <img src="{% static 'img\jkuat-logo-removebg-preview.png' %}" alt="" class="jkuat">
    </nav>
    
    <div class="container">

        <div class="contents" >
            <label for="search">Search</label>
            <input type="text" name="reg" id="search" placeholder="your registration number"
            hx-get="{% url 'generator:form-data' %}"
            hx-trigger="keyup changed:500ms"
            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            hx-target="#search-results"
            >
        </div>
        <div class="search-results" id="search-results">

        </div>
    </div>
</body>
<script src="{% static 'js/min.js' %}" ></script>

</html>

security/templates/results.html

<table>
    <thead>
        <tr>
            <td>REG NO</td>
            <td>FIRST NAME</td>
            <td>GADGET BRAND</td>
            <td>GADGET MODEL</td>
            <td>GADGET OS</td>
            <td>QR CODE</td>
        </tr>
    </thead>
<tbody>
    {% for qs in qs %}
    <tr>
        <td>{{qs.reg_no}}</td>
        <td>{{qs.first_name}}</td>
        <td>{{qs.gadget_brand}}</td>
        <td>{{qs.gadget_model}}</td>
        <td>{{qs.gadget_os}}</td>
        <td><a href="{{qs.qr_code.url}}">Download</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>